set_property IOSTANDARD LVCMOS33 [get_ports out]
set_property IOSTANDARD LVCMOS33 [get_ports select]
set_property IOSTANDARD LVCMOS33 [get_ports x]
set_property IOSTANDARD LVCMOS33 [get_ports y]
set_property PACKAGE_PIN M13 [get_ports x]
set_property PACKAGE_PIN K14 [get_ports y]
set_property PACKAGE_PIN L13 [get_ports select]
set_property PACKAGE_PIN F19 [get_ports out]
